In [2]:
import numpy as np

In [3]:
arr = np.arange(0,21,2)
print(arr)


[ 0  2  4  6  8 10 12 14 16 18 20]


In [4]:
eye = np.eye(3,3)
print(eye)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [5]:
ones = np.ones(16).reshape(4,4)
print(ones)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [6]:
ls = np.linspace(5,50,10)
print(ls)

[ 5. 10. 15. 20. 25. 30. 35. 40. 45. 50.]


In [7]:
py_array = [10, 20, 30, 40, 50]
np_array = np.array(py_array)

print(np_array)


[10 20 30 40 50]


In [11]:
np.random.rand(3,3)

array([[8.46562499e-01, 7.11878093e-01, 4.39611359e-02],
       [3.09172341e-04, 8.38985412e-01, 1.24922806e-01],
       [3.21084616e-01, 1.45140468e-01, 9.69333112e-01]])

In [12]:
np.random.randn(3,3)

array([[ 1.31790373, -0.64513499, -0.59895353],
       [ 1.73649985, -0.24941096,  0.06932655],
       [-1.71572378, -0.07344536,  0.27002483]])

In [35]:
random = np.random.randint(1,10,9).reshape(3,3)
print(np.shape(random))
print(np.size(random))
print(type(random))

(3, 3)
9
<class 'numpy.ndarray'>


In [ ]:
second_array = np.array([5, 10, 15, 20, 25, 30])
print(second_array[0])
print(second_array[-3:])
print(second_array[1:5])

5
[20 25 30]
[10 15 20 25]


In [64]:
mat = np.arange(1, 10).reshape(3, 3)
print(mat)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [65]:
print(mat[1,:])

[4 5 6]


In [63]:
print(mat[:,:2])

[[1 2]
 [4 5]
 [7 8]]


In [ ]:
sub_mat = mat[1:3,1:3]
print(sub_mat)

[[5 6]
 [8 9]]


In [ ]:
mat2 = np.arange(6,15).reshape(3, 3)
print(mat2)


[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [ ]:
mat2_plus_10 = mat2 +10
print(mat2_plus_10)


[[16 17 18]
 [19 20 21]
 [22 23 24]]


In [81]:
mat2[:, 0] *= 2
print(mat2)

[[ 64   7   8]
 [256  10  11]
 [448  13  14]]


In [ ]:

original = np.array([1, 2, 3, 4, 5])


shallow = original.view()
deep = original.copy()
original[0] = 99
print("Original:", original)
print("Shallow Copy:", shallow)
print("Deep Copy:", deep)


Original: [99  2  3  4  5]
Shallow Copy: [99  2  3  4  5]
Deep Copy: [1 2 3 4 5]


In [83]:
arr43 = np.arange(10, 101, 10)
selected = arr43[[0, 3, 5]]
print(selected)


[10 40 60]


In [87]:
arr5 = np.array([3, 7, 2, 9, 12, 5, 10])


max_value = arr5.max()
max_index = arr5.argmax()


min_value = arr5.min()
min_index = arr5.argmin()

print(max_value)
print(max_index)
print( min_value)
print(min_index)

12
4
2
2


In [88]:

arr6 = np.array([1, 2, 3, 4, 5])

sqrt_result = np.sqrt(arr6)
exp_result = np.exp(arr6)
sin_result = np.sin(arr6)
log_result = np.log(arr6)

print(sqrt_result)
print( exp_result)
print(sin_result)
print(log_result)


[1.         1.41421356 1.73205081 2.         2.23606798]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]
